### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by beansbin** [29th-WE-SOPT-iOS-Part/ParkYeBin#13]
## 📌  Feature Issue
서버 API 붙이기 - 로그인, 회원가입

## 📝  To-do
- [x] 홈 화면이 가장 첫 화면이 되게 하기
- [x] 홈에서 로그인 화면으로 화면 전환할 수 있도록 하기
- [x] 로그인 화면에서 다음 버튼 누르면 alert 띄우기
- [x] 로그인 화면에서 다음 버튼에 API 연결하기(성공, 데이터 불일치, 데이터 없음)
- [x] 회원가입 화면에서 다음 버튼 누르면 alert 띄우기
- [x] 회원가입 화면에서 다음 버튼에 API 연결하기(성공, 데이터 불일치, 데이터 없음)

## 📝  도전 과제
- [x] 로그인 name값을 UserDefaults에 저장 후 확인 화면에서 띄워 보여주기
