### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by beansbin** [29th-WE-SOPT-iOS-Part/ParkYeBin#8]
## 📌  Feature Issue
TableView와 CollectionView를 이용해 Youtube 홈 화면 구성하기

## 📝  To-do
- [x] 전체 컴포넌트 간 AutoLayout

### TableView
- [x] TableViewCell Xib 파일 만들기
- [x] TableView 생성 및 Controller 구현
- [x] AutoLayout 잡기

### CollectionView
- [x] CollectionViewCell 만들기
- [x] CollectionView 생성 및 Controller 구현
- [x] AutoLayout 잡기

### 상단 View 만들기
 - [x] 상단 View 만들기
 - [x] AutoLayout 잡기 

### 도전과제
- [x] CollectionView를 사용하여 filter cell 구현하기
